# Put null if you dont want it

SFX:  C:/Users/EXO/Downloads/Sound/SFX
Music: C:/Users/EXO/Downloads/Sound/Music
DataBase: C:/Users/EXO/Downloads/DataBase 
Script: C:/Users/EXO/Downloads/Script
Document: C:/Users/EXO/Downloads/Documents
Program: C:/Users/EXO/Downloads/Program
Archive: C:/Users/EXO/Downloads/Archive
Image: C:/Users/EXO/Downloads/Image
Video: C:/Users/EXO/Downloads/Video
Defult: C:/Users/EXO/Downloads
Clean_Defult: C:/Users/EXO/Downloads/GoogleDownlaods
